# Generated by Django 4.0.1 on 2025-12-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('chromosome', models.CharField(max_length=80, verbose_name='Chromosome')),
                ('location', models.CharField(max_length=80, verbose_name='Location')),
                ('strand', models.CharField(max_length=10, verbose_name='Strand')),
                ('sequence', models.TextField(verbose_name='Sequence')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('expressionValue', models.CharField(blank=True, max_length=50, null=True, verbose_name='Expression Value')),
                ('sampleInformation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sample Information')),
                ('experimentalDesign', models.CharField(blank=True, max_length=50, null=True, verbose_name='Experimental Design')),
                ('lncRNAFunction', models.CharField(blank=True, max_length=50, null=True, verbose_name='LncRNA Function')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference')),
                ('otherInformation', models.TextField(blank=True, null=True, verbose_name='Other Information')),
            ],
        ),
    ]
