# Generated by Django 4.0.1 on 2025-12-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiltrationStepsLncRnaIdentificationPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Table name')),
                ('data', models.JSONField(verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipBetweenChrGeneLncRna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Table name')),
                ('data', models.JSONField(verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='SubdivisionLncRnasAccordingClassCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Table name')),
                ('data', models.JSONField(verbose_name='Data')),
            ],
        ),
    ]
